analyzer:
  language:
    strict-casts: true
    strict-raw-types: false
  errors:
    todo: ignore

linter:
  rules:
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    await_only_futures: true
    cancel_subscriptions: true
    prefer_final_locals: false
    unnecessary_new: true
    use_build_context_synchronously: false
